In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
## Sentences
sent=[
    'the glass of milk',
    'the glass of juice',
    'I am a good boy',
    'I am a good developer',
    'understand the meaning of words',
    'your videos are good',
]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
## One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[8958, 9540, 815, 4320],
 [8958, 9540, 815, 8482],
 [3995, 3609, 9420, 7777, 9279],
 [3995, 3609, 9420, 7777, 1718],
 [2244, 8958, 7012, 815, 6399],
 [8239, 3851, 7268, 7777]]

In [7]:
## Word embedding Representation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

import numpy as np

In [ ]:
set_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=set_length) # make fixed length for all sentence
print(embedded_docs)

[[   0    0    0    0 8958 9540  815 4320]
 [   0    0    0    0 8958 9540  815 8482]
 [   0    0    0 3995 3609 9420 7777 9279]
 [   0    0    0 3995 3609 9420 7777 1718]
 [   0    0    0 2244 8958 7012  815 6399]
 [   0    0    0    0 8239 3851 7268 7777]]


In [10]:
## Feature Representation
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=set_length))
model.compile

<bound method Model.compile of <keras.src.engine.sequential.Sequential object at 0x00000207C012B390>>

In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [13]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 227ms/step


array([[[ 0.00501119,  0.02844529,  0.00740749,  0.01358647,
          0.01406259,  0.01923944, -0.02462581,  0.04726274,
         -0.02681809, -0.01226516],
        [ 0.00501119,  0.02844529,  0.00740749,  0.01358647,
          0.01406259,  0.01923944, -0.02462581,  0.04726274,
         -0.02681809, -0.01226516],
        [ 0.00501119,  0.02844529,  0.00740749,  0.01358647,
          0.01406259,  0.01923944, -0.02462581,  0.04726274,
         -0.02681809, -0.01226516],
        [ 0.00501119,  0.02844529,  0.00740749,  0.01358647,
          0.01406259,  0.01923944, -0.02462581,  0.04726274,
         -0.02681809, -0.01226516],
        [ 0.02345926,  0.00859783, -0.0169548 , -0.03837862,
          0.03637466, -0.01334525,  0.03398303, -0.04616157,
          0.0006861 ,  0.04068882],
        [-0.03610364,  0.03869301, -0.01199558, -0.04236096,
          0.03095943,  0.04338178,  0.00731794,  0.04970368,
          0.04807111,  0.03141001],
        [ 0.00914156,  0.02597893,  0.04330435, -0.0

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0, 8958, 9540,  815, 4320])

In [17]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 179ms/step


array([[ 0.00501119,  0.02844529,  0.00740749,  0.01358647,  0.01406259,
         0.01923944, -0.02462581,  0.04726274, -0.02681809, -0.01226516],
       [ 0.00501119,  0.02844529,  0.00740749,  0.01358647,  0.01406259,
         0.01923944, -0.02462581,  0.04726274, -0.02681809, -0.01226516],
       [ 0.00501119,  0.02844529,  0.00740749,  0.01358647,  0.01406259,
         0.01923944, -0.02462581,  0.04726274, -0.02681809, -0.01226516],
       [ 0.00501119,  0.02844529,  0.00740749,  0.01358647,  0.01406259,
         0.01923944, -0.02462581,  0.04726274, -0.02681809, -0.01226516],
       [ 0.02345926,  0.00859783, -0.0169548 , -0.03837862,  0.03637466,
        -0.01334525,  0.03398303, -0.04616157,  0.0006861 ,  0.04068882],
       [-0.03610364,  0.03869301, -0.01199558, -0.04236096,  0.03095943,
         0.04338178,  0.00731794,  0.04970368,  0.04807111,  0.03141001],
       [ 0.00914156,  0.02597893,  0.04330435, -0.03033677,  0.04206041,
        -0.04510548, -0.01956987, -0.01478111